# Generated by Django 5.1.4 on 2025-01-14 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feelapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrador',
            options={},
        ),
        migrations.AlterModelManagers(
            name='administrador',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='contraseña',
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='email',
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='username',
        ),
        migrations.AlterField(
            model_name='administrador',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
